[package]
name = "tic-tac-toe-logic"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>", "Maciej Zielinski <maciej@casperlabs.io>"]
edition = "2018"

[lib]
doctest = false
bench = false

[dependencies]
num-derive = { version = "0.2.5", default-features = false }
num-traits = { version = "0.2.8", default-features = false }
