[package]
name = "test-mint-token"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[lib]
name = "mint_token_test"
crate-type = ["cdylib"]

[features]
default = []
std = ["contract-ffi/std"]

[dependencies]
contract-ffi = { path = "../../../contract-ffi", package = "casperlabs-contract-ffi" }
