[package]
name = "execution-engine"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>", "Mateusz GÃ³rski <gorski.mateusz@protonmail.ch>"]

[dependencies]
wasmi = "0.4.2"
parity-wasm = "0.31"
pwasm-utils = "0.6"
storage = { path = "../storage" }
common = { path = "../common", features = ["std"] }
wasm-prep = { path = "../wasm-prep" }
clap = "2.32.0"


[[bin]]
name = "engine-standalone"
path = "src/main.rs"

[lib]
name = "execution_engine"
path = "src/lib.rs"

