[workspace]

members = [
    "comm",
    "common",
    "contracts/client/bonding",
    "contracts/client/transfer_to_account",
    "contracts/client/unbonding",
    "contracts/system/mint-token",
    "contracts/system/pos",
    "contracts/system/test-mint-token",
    "contracts/test/add-update-associated-key",
    "contracts/test/remove-associated-key",
    "contracts/test/create-purse-01",
    "contracts/test/ee-221-regression",
    "contracts/test/ee-401-regression",
    "contracts/test/ee-401-regression-call",
    "contracts/test/transfer-to-account-01",
    "contracts/test/transfer-to-account-02",
    "contracts/test/local-state",
    "contracts/test/known-urefs",
    "contracts/test/transfer-purse-to-purse",
    "contracts/test/ee-441-rng-state",
    "contracts/test/get-blocktime",
    "contracts/test/get-caller",
    "contracts/test/get-caller-subcall",
    "contracts/test/main-purse",
    "contracts/test/blessed-urefs-access-rights",
    "contracts/test/transfer-purse-to-account",
    "contracts/test/deserialize-error",
    "contracts/test/ee-539-regression",
    "engine",
    "metrics-scraper",
    "shared",
    "storage",
    "wasm-prep",
]
