[package]
name = "vesting-smart-contract"
version = "0.1.0"
authors = ["Maciej Zielinski <maciej@casperlabs.io>"]
edition = "2018"

[[bin]]
name = "vesting_smart_contract"
path = "src/main.rs"
doctest = false
test = false
bench = false

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../types", package = "casperlabs-types" }
vesting-logic  = { path = "../vesting-logic" }
