[package]
name = "faucet"
version = "0.1.0"
authors = ["Mateusz GÃ³rski <mateusz@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]
bench = false
doctest = false
test = false

[features]
std = ["contract/std", "types/std"]
lib = []

[dependencies]
contract = { path = "../../../contract", package = "casperlabs-contract" }
types = { path = "../../../types", package = "casperlabs-types" }
