[genesis]

name = "casperlabs-devnet"

timestamp = 0

protocol-version = "1.0.0"

mint-code-path = "mint_install.wasm"

pos-code-path = "pos_install.wasm"

initial-accounts-path = "accounts.csv"

[highway]


genesis-era-start = 1583712000000

era-duration = "7days"

booking-duration = "10days"

entropy-duration = "3hours"

voting-period-duration = "2days"

voting-period-summit-level = 0

ftt = 0.1

[deploys]
max-ttl-millis = 86400000
max-dependencies = 10
max-block-size-bytes = 10485760
max-block-cost = 0

[wasm-costs]
regular = 1
div-multiplier = 16
mul-multiplier = 4
mem-multiplier = 2
mem-initial-pages = 4096
mem-grow-per-page = 8192
mem-copy-per-byte = 1
max-stack-height = 65536
opcodes-multiplier = 3
opcodes-divisor = 8
