[package]
name = "shared"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[dependencies]
binascii = "0.1.2"
common = { package = "casperlabs-contract-ffi", path = "../../execution-engine/common" }
