[package]
name = "pos-install"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[features]
default = []
std = ["contract-ffi/std"]

[dependencies]
contract-ffi = { path = "../../../contract-ffi", package = "casperlabs-contract-ffi" }
pos = { path = "../pos", default-features = false, features = ["lib"] }
