[package]
name = "create-test-node-01"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>"]
edition = "2018"

[lib]
name = "create_test_node_01"
crate-type = ["cdylib"]

[dependencies]
shared = { path = "../shared" }
