[package]
name = "pos"
version = "0.1.0"
authors = ["Andreas Fackler <andreas@casperlabs.io>"]
edition = "2018"

[lib]
name = "pos"
crate-type = ["cdylib"]

[features]
default = []
std = ["cl_std/std"]

[dependencies]
cl_std = { path = "../../../contract-ffi", package = "casperlabs-contract-ffi" }
