[package]
name = "pos"
version = "0.1.0"
authors = ["Andreas Fackler <andreas@casperlabs.io>"]
edition = "2018"

[features]
std = ["contract/std", "types/std"]
enable-bonding = []

[dependencies]
base16 = { version = "0.2.1", default-features = false }
contract = { path = "../../../contract", package = "casperlabs-contract" }
proof-of-stake = { path = "../../../proof-of-stake", package = "casperlabs-proof-of-stake" }
types = { path = "../../../types", package = "casperlabs-types" }
