[package]
name = "mint-token"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]
bench = false
doctest = false

[features]
default = []
std = ["contract-ffi/std"]
lib = []

[dependencies]
contract-ffi = { path = "../../../contract-ffi", package = "casperlabs-contract-ffi" }
