version: "3.5"

networks:
  casperlabs:
    external: true

services:
  # Metrics available at http://localhost:9090
  prometheus:
    image: prom/prometheus:v2.7.1
    container_name: prometheus
    volumes:
      - ${PWD}/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      # Mount the file which we'll keep refreshing any time nodes are created or removed.
      - ${PWD}/monitoring/prometheus/targets.yml:/etc/prometheus/targets.yml
    ports:
      - ${CL_PROMETHEUS_PORT}:9090
    networks:
      - casperlabs

  # Dashboard available at http://localhost:3000
  # login credentials are admin/admin
  grafana:
    image: grafana/grafana:5.4.3
    container_name: grafana
    volumes:
      # http://docs.grafana.org/v5.0/administration/provisioning/
      - ${PWD}/monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ${PWD}/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - ${CL_GRAFANA_PORT}:3000
    networks:
      - casperlabs

  # Expose ports from one of the containers to the host.
  # https://hub.docker.com/r/marcnuri/port-forward
  # https://hub.docker.com/r/alpine/socat
  node-http-proxy:
    image: alpine/socat
    container_name: node-http-proxy
    ports:
      - ${CL_SERVER_HTTP_PORT}:40403
    command: "tcp-listen:40403,fork,reuseaddr tcp-connect:node-0:40403"
    networks:
      - casperlabs

