[package]
name = "casperlabs-contract-ffi"
version = "0.2.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"
description = "Library for developing CasperLabs smart contracts."
license = "Apache-2.0"

[features]
default = []
std = []

[dependencies]
wee_alloc = "0.4.3"
