[package]
name = "casperlabs-contract-ffi"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]
edition = "2018"
description = "Library for developing CasperLabs smart contracts."
license = "Apache-2.0"

[features]
default = []
std = []

[dependencies]
byteorder = { version = "1", default-features = false }
wee_alloc = "0.4.2"
