[package]
name = "add_associated_key"
version = "0.1.0"
authors = ["Joe Sacher <joes@casperlabs.io>"]
edition = "2018"

[lib]
name = "add_associated_key"
crate-type = ["cdylib"]

[features]
default = []
std = ["contract-ffi/std"]

[dependencies]
contract-ffi = { package = "casperlabs-contract-ffi", path = "../../../../execution-engine/contract-ffi" }
