[package]
name = "casperlabs-engine-core"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>", "Mateusz GÃ³rski <gorski.mateusz@protonmail.ch>"]

[dependencies]
blake2 = "0.8"
contract-ffi = { path = "../contract-ffi",  package = "casperlabs-contract-ffi", features = ["std", "gens"] }
engine-shared = { path = "../engine-shared", package = "casperlabs-engine-shared" }
engine-storage = { path = "../engine-storage", package = "casperlabs-engine-storage" }
engine-wasm-prep = { path = "../engine-wasm-prep", package = "casperlabs-engine-wasm-prep" }
failure = "0.1.5"
itertools = "0.8.0"
linked-hash-map = "0.5.2"
num-derive = "0.2.5"
num-traits = "0.2.8"
parity-wasm = "0.31"
parking_lot = "0.7.1"
pwasm-utils = "0.6"
rand = "0.6.1"
rand_chacha = "0.1.1"
wasmi = "0.4.2"

[dev-dependencies]
matches = "0.1.8"
proptest = "0.9.2"
wabt = "0.7.4"
