[package]
name = "test-call-hello-name"
version = "0.1.0"
authors = ["Michael Birch <birchmd@casperlabs.io>"]

[lib]
name = "test_helloworld"
crate-type = ["cdylib"]

[dependencies]
common = { package = "casperlabs-contract-ffi", path = "../../../../execution-engine/common/" }
