[package]
name = "test-unbonding-call"
version = "0.1.0"
authors = ["Srinivas Reddy Thatiparthy <srini@casperlabs.io>"]
edition = "2018"

[lib]
name = "test_unbondingcall"
crate-type = ["cdylib"]

[dependencies]
common = { package = "casperlabs-contract-ffi", path = "../../../../execution-engine/contract-ffi" }
