[package]
name = "transfer-to-purse"
version = "0.1.0"
authors = ["MichaÅ‚ Papierski <michal@papierski.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[features]
default = []
std = ["contract-ffi/std"]

[dependencies]
contract-ffi = { path = "../../../contract-ffi", package = "casperlabs-contract-ffi" }
